
version: 2

models:
  - name: fct_bill_actions
    columns:
      - name: bill_id
        tests:
          - relationships:
              to: ref('dim_bills')
              field: bill_id
      - name: action_id
        tests:
          - not_null
          - unique
    

  - name: dim_bills
    columns:
     - name: bill_id
       tests:
        - not_null
        - unique
    tests:
      - dbt_utils.expression_is_true:
          expression: "bipartisan_cosponsor_count <= cosponsor_count"
